### ISSUE TITLE
Native checkbox does not retain correct properties

### ISSUE THREAD

**Issue by ArthurN** [kartik-v/bootstrap-checkbox-x#12]
For 2-state checkboxes, you have to rely on val() being either "1" or "0" to determine whether a Checkbox-X box is indeed checked. This is because checkbox-x does not seem to correctly set the underlying properties on the native checkbox.

For example, on your demo page (http://plugins.krajee.com/checkbox-x/demo), open up the console and run these tests:
```
> ("#input-20").val()
"1"
> $("#input-20").is(':checked')
false
> $("#input-20").checked
false
```

This is also a problem if you want the value to be something else – e.g. "on" or "yes" or whatever.

**Comment by kartik-v** [comment]
This is a pre-requisite as mentioned in the plugin docs. The value has to be one of `1` or `0` or `null` for the three states. Note that the plugin can be initialized on a text input as well which does not have a checked property.

**Comment by kartik-v** [comment]
I will provide a minor enhancement to correct the checkbox states as well.

**Comment by kartik-v** [comment]
I just checked that the steps work fine. The checked property and indeterminate property for checkboxes are automatically set by the plugin:

- if value = 1, the checked property is true
- if value = 0, the checked property is false, 
- if value = null, the indeterminate property is true

note that the value must be one of `0`, `1` or `null` always.
