### ISSUE TITLE
Using space to toggle, scrolls the page

### ISSUE THREAD

**Issue by MojoDK** [kartik-v/bootstrap-checkbox-x#21]
Hi

I've tried the demo here:
http://plugins.krajee.com/checkbox-x/demo

Adn when I navigate using TAB to a checkbox and press space to toggle it, the page scrolls way down. Is it possible to be able to toggle with space without the page scrolling?

Thx

**Comment by kartik-v** [comment]
This has nothing to do with the widget but a behavior to your specific browser (e.g. Chrome).

Clicking space on some browsers triggers the page scroll. [Check a discussion here](http://stackoverflow.com/questions/17010388/do-not-scroll-page-down-when-spacebar-is-clicked).

**Comment by kartik-v** [comment]
This has nothing to do with the widget but a behavior to your specific browser (e.g. Chrome). Try clicking space on this page for example - it will scroll.

Clicking space on some browsers triggers the page scroll. [Check a discussion here](http://stackoverflow.com/questions/17010388/do-not-scroll-page-down-when-spacebar-is-clicked).

**Comment by MojoDK** [comment]
Great thanks!

Spooky useless feature to have space scrolling the page when you have page-up page-down buttons. :)

Thanks again!
