### ISSUE TITLE
Tabindex - why not 0?

### ISSUE THREAD

**Issue by MojoDK** [kartik-v/bootstrap-checkbox-x#22]
Hi

If I place a bootstrap-checkbox-x in the middle of several inputs, then using TAB skips the bootstrap-checkbox-x until the end of last control.

Why not use tabindex="0"? This way it will follow the flow?

Thanks

**Comment by kartik-v** [comment]
New plugin property `tabindex` added which defaults to `1000`. You can set it to `-1` if you need to show it in the beginning. Setting it to `false`, `0` or empty will not assign a tabindex.
