### ISSUE TITLE
Doubleclick markes the line

### ISSUE THREAD

**Issue by MojoDK** [kartik-v/bootstrap-checkbox-x#23]
When I double click a checkbox, then the whole row is marked blue:

![Image of Yaktocat](http://content.screencast.com/users/Mojodk/folders/Snagit/media/dc97a0da-f3ad-4cf5-8729-0bf64da8a7e0/05.29.2015-12.42.png)

Is it possible to detect doubleclick and then set selectionlength to 0?

Thx

**Comment by kartik-v** [comment]
The plugin has nothing to do with your use case. You need to check your rendered markup, CSS and JS to handle this. 

You can try for example [double clicking in the demo](http://plugins.krajee.com/checkbox-x/demo) and see for yourself.

**Comment by kartik-v** [comment]
OK I see this for ENCLOSED LABELS only... will check and update.

**Comment by kartik-v** [comment]
This can be controlled through your markup for enclosing labels. Just check the updated demo and [second last example (no. 5) in advanced usage](http://plugins.krajee.com/checkbox-x/demo#advanced-usage).

**Comment by MojoDK** [comment]
Using Google Chrome, clicking most samples on your website, marks the row blue (as shown above). Everything works fine in IE...

See here:
http://screencast.com/t/UVEJKL8IcAO

**Comment by kartik-v** [comment]
Yes its a browser behavior to show this for full width blocks whenever someone double clicks..

As I mentioned you can control this through the HTML markup. Please check the STYLING for the [SECOND LAST example  (no. 5) in advanced usage](http://plugins.krajee.com/checkbox-x/demo#advanced-usage) where it shows an ENCLOSED LABEL.

**Comment by kartik-v** [comment]
However I am reopening this request to see if an enhancement is possible for this.

**Comment by kartik-v** [comment]
This is resolved now via new styling fixes to the CSS.
