### ISSUE TITLE
Get attribute (i.e. 'id') of parent input ?

### ISSUE THREAD

**Issue by techmantoolz** [kartik-v/bootstrap-checkbox-x#26]
Can't seem to access any attributes of original parent input via change event. How do ?
Thanks in anticipation
TT

**Comment by techmantoolz** [comment]
Anyone have a means to get attributes / data attributes from original HTML declaration ? TIA

**Comment by kartik-v** [comment]
Do not assign the CSS class `cbx` to your input?

You can directly parse the [input change event as mentioned in documentation](http://plugins.krajee.com/checkbox-x#events).
