### ISSUE TITLE
Event change don't fire when threeState = true

### ISSUE THREAD

**Issue by slbtuga** [kartik-v/bootstrap-checkbox-x#29]
Hi.

If I use option enclosedLabel = false and threeState = true, the change event don't fire.
But, change threeState to false, change event works fine.
Here one example http://jsfiddle.net/7ttpfm2d/1/

What I'm doing wrong here?

Thanks.

**Comment by kartik-v** [comment]
Resolved via latest commit.

**Comment by slbtuga** [comment]
Now work well.
Great job.
Thanks
