### ISSUE TITLE
Provide a means to update visual state of checkbox

### ISSUE THREAD

**Issue by steelden** [kartik-v/bootstrap-checkbox-x#33]
Right now there is no way to update visual state of checkbox control if underlying checkbox was modified through DOM manipulations.
This is very unconvinient in situations where 2-way bindings are involved like in Angular.
Can you please add some method to simply refresh control's internal state based on checkbox's current state?

**Comment by kartik-v** [comment]
Hope you read the docs. You can use the plugin `refresh` method as [mentioned in the documentation](http://plugins.krajee.com/checkbox-x#methods).
