### ISSUE TITLE
Bower Install is broken

### ISSUE THREAD

**Issue by j0inty** [kartik-v/bootstrap-checkbox-x#37]
Hi,

with your commit kartik-v/bootstrap-checkbox-x@87ff3e01905fb170e7d97f42ae2bf6686d65e24b the bower install command doesn't work as expected.

If you now try to install the package the npm pull the wrong bootstrap version.

I used nodejs in version 4.0.0 and 4.1.0.

Note:
http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/

"C:\Users\<UserName>\AppData\Roaming\npm\bower.cmd" "install"
bower bootstrap-checkbox-x#1.5.4           cached git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4         validate 1.5.4 against git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap#~3.0                       cached git://github.com/twbs/bootstrap.git#3.0.3
bower bootstrap#~3.0                     validate 3.0.3 against git://github.com/twbs/bootstrap.git#~3.0

regards
j0inty

**Comment by kartik-v** [comment]
Check now.

**Comment by j0inty** [comment]
Best thanks. This did it.


bower bootstrap-checkbox-x#1.5.4           cached git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4         validate 1.5.4 against git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4           cached git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4         validate 1.5.4 against git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4              new version for git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4          resolve git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4              new version for git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4          resolve git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4         download https://github.com/kartik-v/bootstrap-checkbox-x/archive/v1.5.4.tar.gz
bower bootstrap-checkbox-x#1.5.4         download https://github.com/kartik-v/bootstrap-checkbox-x/archive/v1.5.4.tar.gz
bower bootstrap-checkbox-x#1.5.4          extract archive.tar.gz
bower bootstrap-checkbox-x#1.5.4         resolved git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4          extract archive.tar.gz
bower bootstrap-checkbox-x#1.5.4         resolved git://github.com/kartik-v/bootstrap-checkbox-x.git#1.5.4
bower bootstrap-checkbox-x#1.5.4          install bootstrap-checkbox-x#1.5.4

bootstrap-checkbox-x#1.5.4 bower_components\bootstrap-checkbox-x
├── bootstrap#3.3.5
└── jquery#1.11.3
Done.
