### ISSUE TITLE
custom values not working

### ISSUE THREAD

**Issue by mad4hit** [kartik-v/bootstrap-checkbox-x#38]
Hi Kartik, thanks for this plugin.
I'm trying to use the custom value but after declared the pluging doesn't works as aspeceted. When i check the checkbox the flag doesn't apper and the value is not updated.

Thanks 
the code here:

$("chk") .checkboxX({
            size: 'md',
            threeState: false,
            valueChecked: 'true',
            valueUnchecked: 'false'
        });

**Comment by darkvovich** [comment]
+1 data-value-checked string not working!
F ex.
<input type="checkbox" id="module-whatsapp" value="test1" data-value-checked="test1" data-value-unchecked="test2" data-toggle="checkbox-x" data-three-state="false" checked="checked">

**Comment by rhousham** [comment]
Sorry but this is still an issue, using a text box this time
