### ISSUE TITLE
Not working with angularJS app

### ISSUE THREAD

**Issue by artdias90** [kartik-v/bootstrap-checkbox-x#51]
When I add the data attribute to a checkbox inside my ng-app,  nothing happens. Adding the checkbox in the index file works fine, but I need it of course inside my ng-views.

**Comment by kartik-v** [comment]
This is to be handled in your programming code. You need to initialize the jquery plugin for your angular app via the right directives. You may want to search the web on how to initialize jquery plugins in angular apps.
